name = "BiochemFormal"
version = "0.1.0"
defaultTargets = ["BiochemFormal"]

[[lean_lib]]
name = "BiochemFormal"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "master"
